#! /bin/bash

echo  "Please enter an integer :  "
read num

if [  $(expr $num % 2)  ==  1  ]
then
    for (( i=1;i<=$num;i+=2 ))
    do
            for (( j=1;j<=i;j++ ))
        do
                echo -n " *" 

        done
        echo
    done
    for (( i=$num-2;i>=1;i-=2 ))
    do
        for(( j=i;j>=1;--j ))
        do
            echo -n " *"
        done
        echo
    done
else
    echo “Value is not perfect”
fi
